In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

mega = pd.read_excel("../dados.xlsx")
lotofacil = pd.read_excel("../allResultsLotoFacil.xlsx")

quadro = mega.drop(['Concurso', 'Data'], axis=1)
quadroLoto = lotofacil.drop(['Concurso', 'Data'], axis=1)

## Perguntas 
* Qual a quantidade de frequencia de cada número em cada bola?

In [17]:


contagem = {}

for numero in range(1, 61):
    contagem_numero = {}
    for coluna in quadro.columns:
        temp = 0
        for instancia in quadro[coluna]:
            if instancia == numero:
                temp += 1
        
        contagem_numero[coluna] = temp
    
    contagem[numero] = contagem_numero

tabela = pd.DataFrame(contagem).T

tabela.index.name = 'Número'

tabela['Total'] = tabela.sum(axis=1)

tabela['Total Esperado'] = int((2876 * 15)/25)

tabela['Média por bola'] = tabela['Total'] / len(quadro.columns)

tabela['Média por bola Esperada'] = int((1/60)*2876)

tabela['Probabilidade'] = tabela['Total'] / (len(quadro) * len(quadro.columns))

display(tabela)


# Notas: O número 26 tem a menor frequencia comparado com os outros números ele tende
# a média de frequencia dele por bola é 39.5, que por sua vez a probabilidade dele sair 
# em qualquer bola é 0,013.

,bola 1,bola 2,bola 3,bola 4,bola 5,bola 6,Total,Total Esperado,Média por bola,Média por bola Esperada,Probabilidade
Número,,,,,,,,,,,
1,42,47,54,56,39,43,281,1725,46.833333,47,0.016284
2,55,45,56,43,46,46,291,1725,48.500000,47,0.016864
3,39,55,40,34,47,51,266,1725,44.333333,47,0.015415
4,59,44,54,51,47,49,304,1725,50.666667,47,0.017617
5,52,65,42,50,52,55,316,1725,52.666667,47,0.018312
6,52,53,46,41,48,50,290,1725,48.333333,47,0.016806
7,53,43,41,48,45,41,271,1725,45.166667,47,0.015705
8,40,58,44,44,43,54,283,1725,47.166667,47,0.016400
9,43,45,42,44,54,42,270,1725,45.000000,47,0.015647
10,56,63,43,55,62,58,337,1725,56.166667,47,0.019529
11,51,54,49,55,45,46,300,1725,50.000000,47,0.017385
12,42,49,50,37,52,43,273,1725,45.500000,47,0.015821
13,53,41,53,52,52,45,296,1725,49.333333,47,0.017153
14,43,39,47,44,54,50,277,1725,46.166667,47,0.016052
15,36,47,40,42,41,46,252,1725,42.000000,47,0.014604
16,43,46,43,48,60,57,297,1725,49.500000,47,0.017211
17,51,58,50,43,46,58,306,1725,51.000000,47,0.017733
18,35,46,55,52,46,41,275,1725,45.833333,47,0.015936
19,54,42,56,41,40,47,280,1725,46.666667,47,0.016226
20,52,40,48,48,50,44,282,1725,47.000000,47,0.016342
21,38,54,41,37,38,32,240,1725,40.000000,47,0.013908
22,43,49,35,40,39,52,258,1725,43.000000,47,0.014951
23,36,49,53,53,47,63,301,1725,50.166667,47,0.017443
24,49,37,52,42,57,50,287,1725,47.833333,47,0.016632
25,56,41,46,48,44,53,288,1725,48.000000,47,0.016690
26,37,48,34,40,31,47,237,1725,39.500000,47,0.013734
27,54,46,62,44,41,55,302,1725,50.333333,47,0.017501
28,62,41,50,54,53,36,296,1725,49.333333,47,0.017153
29,44,44,54,61,45,39,287,1725,47.833333,47,0.016632
30,60,43,53,47,44,56,303,1725,50.500000,47,0.017559
31,45,40,40,52,45,46,268,1725,44.666667,47,0.015531
32,59,61,44,42,49,51,306,1725,51.000000,47,0.017733
33,46,55,42,50,54,61,308,1725,51.333333,47,0.017849
34,45,40,61,55,54,56,311,1725,51.833333,47,0.018023
35,62,41,51,47,64,36,301,1725,50.166667,47,0.017443
36,47,45,48,54,50,46,290,1725,48.333333,47,0.016806
37,49,46,53,67,45,48,308,1725,51.333333,47,0.017849
38,47,40,60,53,55,53,308,1725,51.333333,47,0.017849
39,44,61,36,41,42,51,275,1725,45.833333,47,0.015936
40,35,47,38,52,48,49,269,1725,44.833333,47,0.015589
41,42,55,59,52,42,48,298,1725,49.666667,47,0.017269
42,47,56,50,44,57,49,303,1725,50.500000,47,0.017559
43,55,53,50,54,48,44,304,1725,50.666667,47,0.017617
44,57,45,49,50,59,41,301,1725,50.166667,47,0.017443
45,47,52,40,42,57,44,282,1725,47.000000,47,0.016342
46,58,48,44,48,52,50,300,1725,50.000000,47,0.017385
47,57,43,40,43,52,40,275,1725,45.833333,47,0.015936
48,35,47,51,40,46,48,267,1725,44.500000,47,0.015473
49,59,57,41,45,41,49,292,1725,48.666667,47,0.016922
50,46,48,38,49,52,50,283,1725,47.166667,47,0.016400
51,51,47,48,51,48,48,293,1725,48.833333,47,0.016980
52,39,44,48,50,56,50,287,1725,47.833333,47,0.016632
53,57,62,51,54,48,57,329,1725,54.833333,47,0.019066
54,47,50,56,53,44,46,296,1725,49.333333,47,0.017153
55,43,42,44,50,29,40,248,1725,41.333333,47,0.014372
56,47,56,63,40,45,49,300,1725,50.000000,47,0.017385
57,41,40,49,45,46,56,277,1725,46.166667,47,0.016052
58,37,49,55,49,43,44,277,1725,46.166667,47,0.016052
59,53,44,50,46,46,39,278,1725,46.333333,47,0.016110
60,49,30,44,64,51,38,276,1725,46.000000,47,0.015994

In [15]:
mega.tail()

      Concurso        Data  bola 1  bola 2  bola 3  bola 4  bola 5  bola 6
2871         5  08/04/1996       1      19      46       6      16       2
2872         4  01/04/1996       6      59      42      27       1       5
2873         3  25/03/1996      36      30      10      11      29      47
2874         2  18/03/1996       9      39      37      49      43      41
2875         1  11/03/1996      41       5       4      52      30      33

In [ ]:
agrupados = tabela.groupby("Total").size()
agrupados.to_excel("Frequenciasiguais.xlsx")
display(agrupados)

In [ ]:

contagem = {}

for numero in range(1, 26):
    contagem_numero = {}
    for coluna in quadroLoto.columns:
        temp = 0
        for instancia in quadroLoto[coluna]:
            if instancia == numero:
                temp += 1
        
        contagem_numero[coluna] = temp
    
    contagem[numero] = contagem_numero

tabela = pd.DataFrame(contagem).T

tabela.index.name = 'Número'

tabela['Total'] = tabela.sum(axis=1)

tabela['Total Esperado'] = int((3421 * 15)/25)

tabela['Média por bola'] = tabela['Total'] / len(quadroLoto.columns)

tabela['Média por bola Esperada'] = int((1/25)*3421)

tabela['Probabilidade'] = tabela['Total'] / (len(quadroLoto) * len(quadroLoto.columns))

display(tabela)

# Notas: O número 26 tem a menor frequencia comparado com os outros números ele tende
# a média de frequencia dele por bola é 39.5, que por sua vez a probabilidade dele sair 
# em qualquer bola é 0,013.

In [ ]:
total_de_Frequencia = tabela['Total']
media = total_de_Frequencia.mean()  # calcula a média

plt.figure(figsize=(15, 8))

plt.bar(total_de_Frequencia.index, total_de_Frequencia.values)
plt.axhline(y=media, color='red', linestyle='--', label=f'Média: {media:.2f}')

plt.title('Frequências com Linha da Média')
plt.xlabel('Número')
plt.ylabel('Total de Frequência')

plt.legend()  # mostra a legenda

plt.tight_layout()
plt.show()

In [ ]:
for v in range(1,26):
    linha = tabela.loc[v]

    linha_filtrada = linha.drop(['Total','Média por bola','Total Esperado','Probabilidade','Média por bola Esperada'], errors='ignore')

    media = linha_filtrada.mean()
    maxima = linha_filtrada.max().max()
    minima = linha_filtrada.min().min()

    plt.figure(figsize=(15,6))
    plt.axhline(y=media, color='red', linestyle='--', label=f'Média: {media:.2f}')
    plt.axhline(y=maxima, color='yellow', linestyle='--', label=f'Maxima: {maxima:.2f}')
    plt.axhline(y=minima, color='blue', linestyle='--', label=f'Minima: {minima:.2f}')
    plt.bar(linha_filtrada.index, linha_filtrada.values)

    plt.title(f"Frequência por bola do número {v}")
    plt.xlabel('Colunas')
    plt.ylabel('Frequência')

    plt.legend()

    plt.tight_layout()
    plt.savefig(f"FrequenciaPorBolaDo{v}")
    plt.show()

In [ ]:
abaixo_da_media = tabela[tabela['Total'] < tabela['Total Esperado']]
display(abaixo_da_media)

In [ ]:
abaixo_da_media = tabela[tabela['Total'] > tabela['Total Esperado']]
display(abaixo_da_media)

In [ ]:
abaixo_da_media = tabela[tabela['Total'] == tabela['Total Esperado']]
display(abaixo_da_media)